### PR TITLE
Circle Fix

### PR DESCRIPTION
**Pull request by wolffan**
O shit I finally sorted CircleCI 😢
- Updated snapkit to use the main lib
- Updated XCGLogger to use main lib and updated the install steps

Please lets not break the build again, it's really a pain to fix

### CODE REVIEW

**Comment by einsteinx2** [comment]
Massive conflicts in the project file...

I tried to sort them out manually, but it looks like you added a bunch of dSYM files to the project. Was that intentional?

Also it looks like ObjcExceptionBridging.framework is only added for iOS?

**Comment by einsteinx2** [comment]
I'm running the carthage update command for XCGLogger for iOS to get the ObjcExceptionBridging framework. In the future, if you update a library you have to use --platform "ios,osx" to get both and then iOS frameworks need an extra manual step in the build phases section.

**Comment by einsteinx2** [comment]
Also for macOS you must add all frameworks as Embedded Binaries in the General section of the project settings or the app won't run (it will compile but not run).

**Comment by einsteinx2** [comment]
Ok I think I've got everything sorted. Just pushed the merge back to this branch so CircleCI will run again before I merge to master.

**Comment by wolffan** [comment]
Should have added  Objc  on both my bad.
The dsym's where added after reading that without them we can't simbolicate some crashes

**Pull request merged**
