### PR TITLE
Fixed kraken currency codes

### PR DESCRIPTION
**Pull request by einsteinx2**

### CODE REVIEW

**Comment by einsteinx2** [comment]
Cutting an internal beta from this branch then we can do an official beta release from master tomorrow after this is merged.

**Comment by einsteinx2** [comment]
Also ignore all the commits except "Fixed Kraken currency codes" as those are from the circleci branch.

**Comment by wolffan** [comment]
This branch seems to need rebasing from master

**Comment by wolffan** [comment]
BTW the code thing looks very much like a hack... is there something in their docs?

**Comment by einsteinx2** [comment]
It is a bit of a hack, unfortunately they use these stupid Z* and X* codes instead of just sending the currency code. Nothing I specifically saw in their docs but it's consistent weird. This is good enough for now but we need to keep an eye on their codes.

**Pull request merged**
